# Generated by Django 4.2 on 2023-05-16 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='book_clubs',
        ),
        migrations.AddField(
            model_name='bookclub',
            name='readers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
