# Generated by Django 4.2 on 2023-05-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='slug',
            field=models.CharField(default='foo', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
