# Generated by Django 4.2 on 2023-05-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0002_remove_reader_book_clubs_bookclub_readers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
