# Generated by Django 4.2 on 2023-05-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0002_bookclub_publicity_alter_bookclubreaders_club_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclubreaders',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
