# Generated by Django 4.2 on 2023-05-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0003_bookclub_description_bookclub_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookclub',
            name='image_url',
        ),
        migrations.AddField(
            model_name='bookclub',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
