# Generated by Django 4.2 on 2023-05-27 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0003_bookclubreaders_is_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('request_status', models.CharField(choices=[('OP', 'Open'), ('VW', 'Viewed'), ('AC', 'Accepted'), ('RJ', 'Rejected')], default='OP', max_length=2)),
                ('book_club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_club.bookclub')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
