# Generated by Django 4.2 on 2023-05-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0005_alter_membershiprequest_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membershiprequest',
            unique_together={('reader', 'book_club')},
        ),
    ]
