# Generated by Django 4.2 on 2023-05-29 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0006_alter_membershiprequest_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershiprequest',
            old_name='request_status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='evaluator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requestor', to=settings.AUTH_USER_MODEL),
        ),
    ]
