# Generated by Django 4.2 on 2023-05-29 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_club', '0007_rename_request_status_membershiprequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='evaluated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='requested',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
