# Generated by Django 4.2 on 2023-05-29 16:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RG', 'Registered'), ('IN', 'Invited'), ('MR', 'Membership Requested'), ('MD', 'Membership Declined'), ('MA', 'Membership Accepted'), ('NR', 'New Reader')], max_length=2)),
                ('action_link', models.URLField(blank=True, null=True)),
                ('generated', models.DateTimeField(default=datetime.datetime.now)),
                ('book_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='book_club.bookclub')),
                ('source_reader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_reader', to=settings.AUTH_USER_MODEL)),
                ('target_reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_reader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=datetime.datetime.now)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notifications.notification')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='viewed_by',
            field=models.ManyToManyField(related_name='viewed_by', through='notifications.NotificationViews', to=settings.AUTH_USER_MODEL),
        ),
    ]
