# Generated by Django 4.2 on 2023-05-28 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_club', '0006_alter_membershiprequest_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MR', 'Membership Requested'), ('MD', 'Membership Declined'), ('MA', 'Membership Accepted'), ('NM', 'New Member')], max_length=2)),
                ('action_link', models.URLField()),
                ('generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book_club.bookclub')),
            ],
        ),
        migrations.CreateModel(
            name='ReaderNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notifications.notification')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='notified_readers',
            field=models.ManyToManyField(through='notifications.ReaderNotifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='source_reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_reader', to=settings.AUTH_USER_MODEL),
        ),
    ]
